timemates/backend

- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/TimersRepository.kt
- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/datasource/TimersDatabaseDataSource.kt
- adapters/repositories-integration/src/test/kotlin/org/tomadoro/backend/repositories/integration/test/TimersRepositoryTest.kt
- application/src/main/kotlin/org/tomadoro/backend/application/results/LeaveTimerResult.kt
- application/src/main/kotlin/org/tomadoro/backend/application/results/serializer/ResultsSerializersModule.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/setupRoutes.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/timer/leave.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/timer/root.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/repositories/TimersRepository.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/usecases/timers/LeaveTimerUseCase.kt
- use-cases/src/test/kotlin/org/tomadoro/backend/repositories/MockedTimersRepository.kt
**Is it breaking change?**
No, it is new feature
**Have you synchronized changes with other repositories?**
Not yet.
**Specify linked issues or discussions**
close #2
> feat: added ability to leave from the timer

- application/src/main/kotlin/org/tomadoro/backend/application/results/KickTimerUserResult.kt
- application/src/main/kotlin/org/tomadoro/backend/application/results/serializer/ResultsSerializersModule.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/setupRoutes.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/timer/kickUser.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/timer/root.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/usecases/timers/KickTimerUserUseCase.kt
**Is it breaking change?**
No, just new feature
**Have you synchronized changes with other repositories?**
Not yet.
**Explain why this change is important**
Check #14 
**Specify linked issues or discussions**
close #14 
**Additional information**
I've added next route:
- **POST** `timers/members/kick`
> feat: added kick user functionality

- application/src/main/kotlin/org/tomadoro/backend/application/plugins/AuthorizationPlugin.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/setupRoutes.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/timer/updates.kt
- application/src/main/kotlin/org/tomadoro/backend/application/types/TimerUpdate.kt
- application/src/main/kotlin/org/tomadoro/backend/application/types/serializer/TypesSerializersModule.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/repositories/SessionsRepository.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/usecases/timers/JoinSessionUseCase.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/usecases/timers/LeaveSessionUseCase.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/usecases/timers/notes/AddNoteUseCase.kt
> feat: added new events for updates

- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/TimersRepository.kt
- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/datasource/DbTimersDatabaseDataSource.kt
- application/src/main/kotlin/org/tomadoro/backend/application/results/GetMembersResult.kt
- application/src/main/kotlin/org/tomadoro/backend/application/results/serializer/ResultsSerializersModule.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/setupRoutes.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/timer/getMembers.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/timer/root.kt
- application/src/main/kotlin/org/tomadoro/backend/application/types/value/PageToken.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/repositories/TimersRepository.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/usecases/timers/GetMembersUseCase.kt
- use-cases/src/test/kotlin/org/tomadoro/backend/repositories/MockedTimersRepository.kt
> feat: added get members request

- application/src/main/kotlin/org/tomadoro/backend/application/routes/timer/getMembers.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/timer/getTimers.kt
- application/src/main/kotlin/org/tomadoro/backend/application/types/value/PageToken.kt
- domain/src/main/kotlin/org/tomadoro/backend/domain/PageToken.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/usecases/timers/GetMembersUseCase.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/usecases/timers/GetTimersUseCase.kt
> feat: page tokens

- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/NotesRepository.kt
- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/datasource/DbTimerNotesDatasource.kt
- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/datasource/DbTimerNotesViewsDataSource.kt
- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/tables/TimerNotesTable.kt
- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/tables/TimerNotesViewsTable.kt
- adapters/repositories-integration/src/test/kotlin/org/tomadoro/backend/repositories/integration/test/NotesRepositoryTest.kt
- application/src/main/kotlin/org/tomadoro/backend/application/results/ViewAllUserNotesResult.kt
- application/src/main/kotlin/org/tomadoro/backend/application/results/serializer/ResultsSerializersModule.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/setupRoutes.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/timer/notes/viewAll.kt
- application/src/main/kotlin/org/tomadoro/backend/application/types/Note.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/repositories/NotesRepository.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/usecases/timers/notes/AddNoteUseCase.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/usecases/timers/notes/GetNotesUseCase.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/usecases/timers/notes/views/ViewAllUserNotesUseCase.kt
> feat: added `isViewed`

- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/SessionsRepository.kt
- application/src/main/kotlin/org/tomadoro/backend/application/results/GetMembersInSessionResult.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/setupRoutes.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/timer/getMembersInSession.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/timer/root.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/repositories/SessionsRepository.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/usecases/timers/GetMembersInSessionUseCase.kt
- use-cases/src/test/kotlin/org/tomadoro/backend/repositories/MockedSessionsRepository.kt
- use-cases/src/test/kotlin/org/tomadoro/backend/usecases/timers/SessionTest.kt
> feat: added get members in session request

- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/NotesRepository.kt
- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/datasource/DbTimerNotesDatasource.kt
- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/tables/internal/CustomBooleanFunction.kt
- application/src/main/kotlin/org/tomadoro/backend/application/results/GetLatestUserNotesResult.kt
- application/src/main/kotlin/org/tomadoro/backend/application/results/serializer/ResultsSerializersModule.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/setupRoutes.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/timer/notes/getLastUserNotes.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/timer/notes/root.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/timer/root.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/repositories/NotesRepository.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/usecases/timers/notes/GetLatestUserNotesUseCase.kt
> feat: added request for getting list of recent notes of the users

- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/TimerActivityRepository.kt
- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/TimersRepository.kt
- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/datasource/DbTimerActivityDataSource.kt
- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/datasource/DbTimersDatabaseDataSource.kt
- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/tables/TimerActivityTable.kt
- adapters/repositories-integration/src/main/kotlin/org/tomadoro/backend/repositories/integration/tables/TimerParticipantsTable.kt
- adapters/repositories-integration/src/test/kotlin/org/tomadoro/backend/repositories/integration/test/TimersRepositoryTest.kt
- application/src/main/kotlin/org/tomadoro/backend/application/routes/setupRoutes.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/repositories/TimerActivityRepository.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/repositories/TimersRepository.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/usecases/timers/StartTimerUseCase.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/usecases/timers/StopTimerUseCase.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/usecases/timers/members/invites/JoinByInviteUseCase.kt
- use-cases/src/main/kotlin/org/tomadoro/backend/usecases/timers/notes/AddNoteUseCase.kt
- use-cases/src/test/kotlin/org/tomadoro/backend/repositories/MockedTimerActivityRepository.kt
- use-cases/src/test/kotlin/org/tomadoro/backend/repositories/MockedTimersRepository.kt
- use-cases/src/test/kotlin/org/tomadoro/backend/usecases/timers/SessionTest.kt
- use-cases/src/test/kotlin/org/tomadoro/backend/usecases/timers/StartDetailedTimerUseCaseTest.kt
- use-cases/src/test/kotlin/org/tomadoro/backend/usecases/timers/StopDetailedTimerUseCaseTest.kt
- use-cases/src/test/kotlin/org/tomadoro/backend/usecases/timers/invites/JoinByInviteUseCaseTest.kt
> feat: timers are now sorted by last activity time & join time

- infrastructure/grpc/build.gradle.kts
- infrastructure/grpc/src/main/proto/io/timemates/api/authorizations/AuthorizationService.proto
- infrastructure/grpc/src/main/proto/io/timemates/api/authorizations/requests/ConfirmAuthorizationRequest.proto
- infrastructure/grpc/src/main/proto/io/timemates/api/authorizations/requests/GetAuthorizationsRequest.proto
- infrastructure/grpc/src/main/proto/io/timemates/api/files/FilesService.proto
- infrastructure/grpc/src/main/proto/io/timemates/api/timers/TimersService.proto
- infrastructure/grpc/src/main/proto/io/timemates/api/timers/requests/CreateTimerRequest.proto
- infrastructure/grpc/src/main/proto/io/timemates/api/timers/requests/EditTimerInfoRequest.proto
- infrastructure/grpc/src/main/proto/io/timemates/api/timers/requests/GetTimersRequest.proto
- infrastructure/grpc/src/main/proto/io/timemates/api/timers/requests/RemoveTimerRequest.proto
- infrastructure/grpc/src/main/proto/io/timemates/api/timers/requests/members/GetMembersRequest.proto
- infrastructure/grpc/src/main/proto/io/timemates/api/timers/requests/members/invites/CreateInviteRequest.proto
- infrastructure/grpc/src/main/proto/io/timemates/api/users/UsersService.proto
closes #63 
closes #64 
closes #65 
closes #66
> #56: GRPC Stubs

- data/src/main/kotlin/io/timemates/backend/data/files/datasource/FileEntityMapper.kt
- data/src/main/kotlin/io/timemates/backend/data/files/datasource/LocalFilesDataSource.kt
- data/src/main/kotlin/io/timemates/backend/data/files/datasource/PostgresqlFilesDataSource.kt
- data/src/main/kotlin/io/timemates/backend/data/users/datasource/PostgresqlUsersDataSource.kt
- data/src/test/kotlin/io/timemates/backend/data/files/FileEntityMapperTest.kt
- data/src/test/kotlin/io/timemates/backend/data/files/datasource/PostgresqlFilesDataSourceTest.kt
- domain/src/main/kotlin/io/timemates/backend/files/types/File.kt
> #52 Cover files data layer with tests

- data/build.gradle.kts
- data/src/main/kotlin/io/timemates/backend/data/files/datasource/PostgresqlFilesDataSource.kt
- data/src/main/kotlin/io/timemates/backend/data/users/datasource/PostgresqlUsersDataSource.kt
> refactor (#100): refactor all newSuspendTransaction to suspendedTransaction from :features:exposedUtils

- data/build.gradle.kts
- data/src/test/kotlin/io/timemates/backend/data/files/FileEntityMapperTest.kt
- data/src/test/kotlin/io/timemates/backend/data/users/UserEntitiesMapperTest.kt
- data/src/test/kotlin/io/timemates/backend/data/users/UsersRepositoryTest.kt
- domain/build.gradle.kts
- domain/src/test/kotlin/io/timemates/backend/auth/usecases/AuthByEmailUseCaseTest.kt
- domain/src/test/kotlin/io/timemates/backend/auth/usecases/ConfigureNewAccountUseCaseTest.kt
- features/test-utils/src/main/kotlin/io/timemates/backend/testing/validation/createOrAssert.kt
> feat (#99): replace createOrThrow with createOrAssert

- infrastructure/application/src/main/kotlin/io/timemates/backend/application/Application.kt
> fix (#140): authorization interceptor is registering now

- app/src/main/kotlin/io/timemates/backend/application/dependencies/AuthorizationsModule.kt
- app/src/main/kotlin/io/timemates/backend/application/dependencies/CommonModule.kt
- app/src/main/kotlin/io/timemates/backend/application/dependencies/ServicesModule.kt
- app/src/main/kotlin/io/timemates/backend/application/dependencies/TimersModule.kt
- app/src/main/kotlin/io/timemates/backend/application/dependencies/UsersModule.kt
I don't understand some parts of this task, so I am sure that there a lot of errors . Also I have not changed some string because I don't know will my changes brake something or not.
> refactor(#13(4+3)): Optimize koin dependencies declarations

- app/build.gradle.kts
- app/src/main/kotlin/io/timemates/backend/application/Application.kt
- gradle/libs.versions.toml
added new service - ProtoReflectionService for debug and test services
> feat (#149): service reflection for debug

- core/src/test/kotlin/io/timemates/backend/auth/usecases/AuthByEmailUseCaseTest.kt
- core/src/test/kotlin/io/timemates/backend/auth/usecases/GetAuthorizationUseCaseTest.kt
- core/src/test/kotlin/io/timemates/backend/auth/usecases/GetAuthorizationsUseCaseTest.kt
- core/src/test/kotlin/io/timemates/backend/auth/usecases/GetCurrentTimerSessionUseCaseTest.kt
- core/src/test/kotlin/io/timemates/backend/auth/usecases/GetUserIdByAccessTokenUseCaseTest.kt
- core/src/test/kotlin/io/timemates/backend/auth/usecases/RefreshTokenUseCaseTest.kt
- core/src/test/kotlin/io/timemates/backend/auth/usecases/RemoveAccessTokenUseCaseTest.kt
> feat(#49): authorization domain tests

- data/src/main/kotlin/io/timemates/backend/data/authorization/PostgresqlAuthorizationsRepository.kt
- data/src/main/kotlin/io/timemates/backend/data/timers/PostgresqlTimersRepository.kt
- data/src/main/kotlin/io/timemates/backend/data/timers/db/TableTimersDataSource.kt
- data/src/main/kotlin/io/timemates/backend/data/timers/db/entities/DbTimer.kt
- data/src/main/kotlin/io/timemates/backend/data/timers/db/entities/TimersPageToken.kt
- data/src/main/kotlin/io/timemates/backend/data/timers/db/tables/TimersTable.kt
- data/src/main/kotlin/io/timemates/backend/data/timers/mappers/TimersMapper.kt
- data/src/test/kotlin/io/timemates/backend/data/timers/datasource/TableTimersDataSourceTest.kt
> fix&tests: Timers Database requests

- app/build.gradle.kts
- core/types/src/main/kotlin/org/timemates/backend/types/auth/Authorization.kt
- features/auth/data/src/main/kotlin/org/timemates/backend/auth/data/PostgresqlAuthorizationsRepository.kt
- features/auth/data/src/main/kotlin/org/timemates/backend/auth/data/db/TableAuthorizationsDataSource.kt
- features/auth/data/src/main/kotlin/org/timemates/backend/auth/data/mapper/AuthorizationsMapper.kt
- features/auth/data/src/test/kotlin/org/timemates/backend/auth/data/test/db/TableAuthorizationsDataSourceTest.kt
- features/auth/domain/src/main/kotlin/org/timemates/backend/auth/domain/repositories/AuthorizationsRepository.kt
- features/auth/domain/src/main/kotlin/org/timemates/backend/auth/domain/usecases/RefreshAccessTokenUseCase.kt
- features/auth/domain/src/test/kotlin/org/timemates/backend/auth/usecases/RefreshTokenUseCaseTest.kt
- infrastructure/rsocket-api/src/main/kotlin/org/timemates/api/rsocket/auth/AuthMappers.kt
> feat&fix: refresh hash generation on renew

- core/types/src/main/kotlin/org/timemates/backend/types/common/value/PageSize.kt
- features/timers/data/src/main/kotlin/org/timemates/backend/timers/data/CoPostgresqlTimerSessionRepository.kt
- features/timers/data/src/main/kotlin/org/timemates/backend/timers/data/PostgresqlTimerInvitesRepository.kt
- features/timers/data/src/main/kotlin/org/timemates/backend/timers/data/PostgresqlTimersRepository.kt
- features/timers/data/src/main/kotlin/org/timemates/backend/timers/data/db/TableTimerInvitesDataSource.kt
- features/timers/data/src/main/kotlin/org/timemates/backend/timers/data/db/TableTimerParticipantsDataSource.kt
- features/timers/data/src/main/kotlin/org/timemates/backend/timers/data/db/TableTimersDataSource.kt
- features/timers/data/src/main/kotlin/org/timemates/backend/timers/data/db/TableTimersSessionUsersDataSource.kt
- features/timers/data/src/test/kotlin/org/timemates/backend/timers/data/test/datasource/TableTimersDataSourceTest.kt
- features/timers/domain/src/main/kotlin/org/timemates/backend/timers/domain/repositories/TimerInvitesRepository.kt
- features/timers/domain/src/main/kotlin/org/timemates/backend/timers/domain/repositories/TimerSessionRepository.kt
- features/timers/domain/src/main/kotlin/org/timemates/backend/timers/domain/repositories/TimersRepository.kt
- features/timers/domain/src/main/kotlin/org/timemates/backend/timers/domain/usecases/GetTimersUseCase.kt
- features/timers/domain/src/main/kotlin/org/timemates/backend/timers/domain/usecases/members/GetMembersInSessionUseCase.kt
- features/timers/domain/src/main/kotlin/org/timemates/backend/timers/domain/usecases/members/GetMembersUseCase.kt
- features/timers/domain/src/main/kotlin/org/timemates/backend/timers/domain/usecases/members/invites/GetInvitesUseCase.kt
- infrastructure/rsocket-api/src/main/kotlin/org/timemates/api/rsocket/timers/TimersService.kt
- infrastructure/rsocket-api/src/main/proto/org/timemates/api/authorizations/requests/GetAuthorizationsRequest.proto
- infrastructure/rsocket-api/src/main/proto/org/timemates/api/timers/members/invites/requests/GetInvitesRequest.proto
- infrastructure/rsocket-api/src/main/proto/org/timemates/api/timers/members/requests/GetMembersRequest.proto
- infrastructure/rsocket-api/src/main/proto/org/timemates/api/timers/requests/GetTimersRequest.proto
> feat(#179): custom page sizes for pagination
